name: build_and_test

on:
  push:
    branches:
      - master
  pull_request:

permissions: read-all

jobs:
  build:
    name: ${{ matrix.os }} - Build & Test
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: Cache Conan Packages
        uses: actions/cache@v2
        with:
          path: ~/.conan/data
          key: ${{ runner.os }}-conan-${{ hashFiles('**/.conan') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup Conan
        run: |
          conan install . --build missing --profile ./.conan/profiles/workflows/${{ matrix.os }}

      - name: Run CMake
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DENJINSDK_BUILD_SHARED=ON -DENJINSDK_BUILD_TESTS=ON

      - name: Build
        run: |
          cmake --build . --config Release

      - name: Test
        run: |
          ctest --verbose --build-config Release
